import type { Metadata } from "next";
import { Libre_Baskerville, JetBrains_Mono } from "next/font/google";
import localFont from "next/font/local";
import { Providers } from "@/components/providers";
import "./globals.css";

// Libre Baskerville - default body/serif font (from Google)
const libreBaskerville = Libre_Baskerville({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  variable: "--font-libre-baskerville",
  display: "swap",
});

// JetBrains Mono - monospace font (from Google)
const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-jetbrains-mono",
  display: "swap",
});

// Compagnon - for headings
const compagnon = localFont({
  src: [
    { path: "./fonts/compagnon/Compagnon-Light.woff2", weight: "300", style: "normal" },
    { path: "./fonts/compagnon/Compagnon-Roman.woff2", weight: "400", style: "normal" },
    { path: "./fonts/compagnon/Compagnon-Italic.woff2", weight: "400", style: "italic" },
    { path: "./fonts/compagnon/Compagnon-Medium.woff2", weight: "500", style: "normal" },
    { path: "./fonts/compagnon/Compagnon-Bold.woff2", weight: "700", style: "normal" },
  ],
  variable: "--font-compagnon",
  display: "swap",
});

// Ruina variants - display/decorative fonts
const ruinaFlor = localFont({
  src: "./fonts/ruina/FlorDeRuina-Flor.woff2",
  variable: "--font-ruina-flor",
  display: "swap",
});

const ruinaFractura = localFont({
  src: "./fonts/ruina/FlorDeRuina-Fractura.woff2",
  variable: "--font-ruina-fractura",
  display: "swap",
});

const ruinaGermen = localFont({
  src: "./fonts/ruina/FlorDeRuina-Germen.woff2",
  variable: "--font-ruina-germen",
  display: "swap",
});

const ruinaRuina = localFont({
  src: "./fonts/ruina/FlorDeRuina-Ruina.woff2",
  variable: "--font-ruina-ruina",
  display: "swap",
});

const ruinaSemilla = localFont({
  src: "./fonts/ruina/FlorDeRuina-Semilla.woff2",
  variable: "--font-ruina-semilla",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${libreBaskerville.variable} ${jetbrainsMono.variable} ${compagnon.variable} ${ruinaFlor.variable} ${ruinaFractura.variable} ${ruinaGermen.variable} ${ruinaRuina.variable} ${ruinaSemilla.variable} antialiased`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
